config/routes.rb
DeviceInventory::Application.routes.draw do

  get '/signin' => 'sessions#new'
  delete'/signout' => 'sessions#destroy'

  resources :books do
    collection do
      get :search
      get :export
      get :unavailable
      post :import
      get :my_books_current
      get :my_books_history
      get :my_books_waiting
    end

    member do
      put :ask
      put :receive
      put :make_unavailable
      put :make_available
      put :queue_request
      put :dequeue_request
      put  :ask_book
      post :ask_book
      get  :ask_book
      post :queue_request
      get  :queue_request
      post :dequeue_request
      get  :dequeue_request
      
    end

    resources :accessories
    resources :reviews
    resources :events, only: [:index]
  end

  resources :users do
    collection do
      get :search
    end
  end

  resources :requests, only: [:index] do
    member do
      put :approve
      put :reject
    end
  end

  resources :sessions

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :book_types
    resources :administrators do
      collection do
        get :search
      end
    end
  end
  
  match 'book_types' => 'books#book_types'
  match 'authentication' => 'sessions#authenticate'

  root :to => 'books#index'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :admin_required

  def index
    @administrators = Administrator.all
    @book_types = BookType.all
    #@accessory_types = AccessoryType.all

    @administrator = Administrator.new
    @book_type = BookType.new
   # @accessory_type = AccessoryType.new
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.haml
%h3 Administrators
%table#administrators.table.table-striped.table-bordered
  %thead
    %tr
      %th Name
      %th Location
      %th Mailing 
      %th
  %tbody
    - @administrators.each do |administrator|
      %tr
        %td= administrator.username
        %td= administrator.location.location_name
        %td= administrator.is_request_mail_enabled? ? "Enabled" : "Disabled"
        %td= link_to (content_tag(:i, '', class: 'icon-remove')), admin_administrator_path(administrator), method: :delete, confirm: 'Are you sure?'
    %tr
      %td
        = form_for [:admin, @administrator], html: {class: 'form-inline'} do |f|
          = f.text_field :username, placeholder: 'LDAP Username', class: 'typeahead', autocomplete: 'off'
          = f.select     :location_id, Location.all.collect {|p| [ p.location_name, p.id ] }
          /= f.select     :location, [['WH-BlockC-7', 'WH-BlockC-7'], ['WH-BlockA-2', 'WH-BlockA-2'], ['WH-BlockA-3', 'WH-BlockA-3'], ['WH-BlockA-6', 'WH-BlockA-6'], ['Hitech', 'Hitech'], ['Chennai', 'Chennai'], ['Bangalore', 'Bangalore'], ['USA', 'USA']]
          

          = f.check_box  :is_request_mail_enabled
          = f.label :is_request_mail_enabled, "Enable Mailing"
          = f.submit 'Add Administrator', class: 'btn btn-primary'
      %td
      %td
      %td

.row-fluid
  .span6
    %h3 Book Types
    %table#device-types.table.table-striped.table-bordered
      %thead
        %tr
          %th Name
      %tbody
        - @book_types.each do |book_type|
          %tr
            %td= book_type.name
        %tr
          %td
            = form_for [:admin, @book_type], html: {class: 'form-inline'} do |f|
              = f.text_field :name, placeholder: 'Book Type'
              = f.submit 'Add Book Type', class: 'btn btn-primary'

  / .span6
  /   %h3 Accessory Types
  /   %table#accessory-types.table.table-striped.table-bordered
  /     %thead
  /       %tr
  /         %th Name
  /     %tbody
  /       - @accessory_types.each do |accessory_type|
  /         %tr
  /           %td= accessory_type.name
  /       %tr
  /         %td
  /           = form_for [:admin, @accessory_type], html: {class: 'form-inline'} do |f|
  /             = f.text_field :name, placeholder: 'Accessory Type'
  /             = f.submit 'Add Accessory Type', class: 'btn btn-primary'

.row-fluid
  %h3= link_to "Unavailable books (#{Book.unavailable.count})", unavailable_books_path, rel: 'tooltip', title: t('books.unavailable')