config/routes.rb
DeviceInventory::Application.routes.draw do

  get '/signin' => 'sessions#new'
  delete'/signout' => 'sessions#destroy'

  resources :books do
    collection do
      get :search
      get :export
      get :unavailable
      post :import
      get :my_books_current
      get :my_books_history
      get :my_books_waiting
    end

    member do
      put :ask
      put :receive
      put :make_unavailable
      put :make_available
      put :queue_request
      put :dequeue_request
      put  :ask_book
      post :ask_book
      get  :ask_book
      post :queue_request
      get  :queue_request
      post :dequeue_request
      get  :dequeue_request
      
    end

    resources :accessories
    resources :reviews
    resources :events, only: [:index]
  end

  resources :users do
    collection do
      get :search
    end
  end

  resources :requests, only: [:index] do
    member do
      put :approve
      put :reject
    end
  end

  resources :sessions

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :book_types
    resources :administrators do
      collection do
        get :search
      end
    end
  end
  
  match 'book_types' => 'books#book_types'
  match 'authentication' => 'sessions#authenticate'

  root :to => 'books#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :book_id, :owner, :possessor, :from_date, :to_date

  attr_accessor :send_email
  # Associations
  belongs_to :book

  # Scopes
  scope :pending, where(state: :pending)

  # Validations
  validates :from_date, presence: true

  # Callback
  after_create :send_request_email, :unless => Proc.new{ self.send_email == false }

  # State Machine
  state_machine :state, :initial => :pending do
    event :reject do
      transition :pending => :archived
    end
    event :approve do
      transition :pending => :issued
    end
    event :archive do
      transition :issued => :archived
    end
  end

  def reject_with_reason(reason)
    self.reject
    BookMailer.rejection_email(self.owner, self.requestor, self.book, reason).deliver
  end
  
  
  def self.is_pending(requestor)
    where("requestor = ? and  state = ?", requestor , "pending")
  end
  

  def self.pending_count(username)
    admin = Administrator.find_by_username(username)
    if  admin.present?
       Request.joins(:book).pending.where("books.location_id = ?","#{admin.location.id}").size
    else
      0
    end
  end

  def self.has_max_req_reached?(username)
     Request.where("requestor like ? and  state  in (?, ?)", "#{username}", "pending", "issued" ).size >= 2
  end

  private

  def send_request_email    
    admins = Administrator.find_all_by_location_id(self.book.location_id).select{|admin| admin.is_request_mail_enabled == true}
    admins.each do |admin|
      BookMailer.request_email(admin.username, self.requestor, self.book).deliver
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :login_required 

  def index
    admin = Administrator.find_by_username(current_user)    
    @requests = Request.joins(:book).pending.where("books.location_id = ?","#{admin.location_id}")
  end

  def approve
    @req = Request.find(params[:id])
    @req.owner = current_user
    respond_to do |format|
      if @req.approve
        format.html { redirect_to requests_path, notice: "Successfully approved the request and an email has been sent to `#{@req.requestor}`" }
      else
        format.html { redirect_to requests_path, notice: "Unable to approve the request" }
      end
    end
  end

  def reject
    @req = Request.find(params[:id])
    @req.owner = current_user
    respond_to do |format|
      if @req.reject_with_reason(params[:reason])
        format.html { redirect_to requests_path, notice: "Successfully rejected the request" }
      else
        format.html { redirect_to requests_path, notice: "Unable to reject the request" }
      end
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_reject_form_template.html.haml
%script#reject-form-template{type: 'text/x-jquery-tmpl'}
  .modal-header
    %h3
      Reject the request from ${requestor}
      %button.close{"data-dismiss" => "modal", :type => "button"}
        %i.icon-remove
  .modal-body

    %form.reject_request.form.form-vertical{"accept-charset" => "UTF-8", :action => "/requests/${requestId}/reject", :method => "post", :id => "reject_request_${requestId}"}
      %div{:style => "margin:0;padding:0;display:inline"}
        %input{:name => "utf8", :type => "hidden", :value => "✓"}/
        %input{:name => "_method", :type => "hidden", :value => "put"}/
        %input{:name => "authenticity_token", :type => "hidden", :value => form_authenticity_token}/
      %div
        You're rejecting a request raised by ${requestor}. It'd be great if you could provide with the reason for rejection, which would in turn be intimated to the user via email.
      .reason
        = label_tag 'reason', 'Reason for rejection'
        = text_area_tag 'reason'
      %p.centered-info
        %input.reject-button.btn.btn-warning{:type => :submit, :value => 'Reject'}
        .progress.progress-striped.active.hide
          .bar{style: 'width: 100%'}
  .modal-footer
    .action-buttons
      %a.btn{"data-dismiss" => "modal"} Close

app/views/requests/index.html.haml
%h3 Book Requests

- if @requests.empty?
  No pending book requests at the moment.
- else
  %table.table.table-striped#requests-list
    %thead
      %tr
        %th Book Title
        %th Requested By
        %th Date
        %th
    - @requests.each do |req|
      %tbody
        %tr{id: "request-row-#{req.id}", class: "request-row"}
          %td= link_to device_name(req.book), book_path(req.book)
          %td{id: "requestor-#{req.id}"}
            = req.requestor
          %td= request_datespan(req)
          %td
            = link_to 'Approve', approve_request_path(req), method: :put, class: 'btn btn-primary'
            = link_to 'Reject', reject_request_path(req), id: "reject-request-#{req.id}", class: 'btn btn-warning reject-request'

#reject-form.modal.fade
= render 'reject_form_template'