config/routes.rb
DeviceInventory::Application.routes.draw do

  get '/signin' => 'sessions#new'
  delete'/signout' => 'sessions#destroy'

  resources :books do
    collection do
      get :search
      get :export
      get :unavailable
      post :import
      get :my_books_current
      get :my_books_history
      get :my_books_waiting
    end

    member do
      put :ask
      put :receive
      put :make_unavailable
      put :make_available
      put :queue_request
      put :dequeue_request
      put  :ask_book
      post :ask_book
      get  :ask_book
      post :queue_request
      get  :queue_request
      post :dequeue_request
      get  :dequeue_request
      
    end

    resources :accessories
    resources :reviews
    resources :events, only: [:index]
  end

  resources :users do
    collection do
      get :search
    end
  end

  resources :requests, only: [:index] do
    member do
      put :approve
      put :reject
    end
  end

  resources :sessions

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :book_types
    resources :administrators do
      collection do
        get :search
      end
    end
  end
  
  match 'book_types' => 'books#book_types'
  match 'authentication' => 'sessions#authenticate'

  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

  attr_accessible :condition,  :product, :title, :publication, :link_for_review, :phone_num,  :book_type_id, :state, :book_photo, :book_photo_file_name, :book_photo_file_size, :book_photo_content_type, :owner, :possessor, :property_of, :author,  :created_by, :updated_by, :location_id, :isbn, :image_link
         
  attr_accessor :owner_name, :possesser_name, :book_possessor

  # Associations
  has_many :reviews, dependent: :destroy
  has_many :requests
  has_many :events
  belongs_to :book_type  
  belongs_to :location
  #accepts_nested_attributes_for :accessories, allow_destroy: true

  # Validations
  #validates :mac_addr,   format: {with: %r|^(\h\h:){5}\h\h$|, message: "should be 48-bit hexadecimal string", allow_blank: true}
  #validates :imei,       format: {with: %r|^\d{15}(\d\d)?$|,  message: "should be 15 or 17-digit",            allow_blank: true}
  validates :phone_num,  format: {with: %r|^[1-9]\d{9}$|,     message: "should be 10-digit",                  allow_blank: true}
 # validates :serial_num, uniqueness: true,                    presence: true
  validates :title, :author, :location_id , presence: true
  # Scopes
  scope :unavailable, where(state: :not_available)
  
  # Paperclip
  has_attached_file :book_photo,
    styles: {thumb: "100x100#", small: "250x250>"},
    storage: :s3,
    s3_credentials: "#{Rails.root}/config/s3.yml",
    path: "/:style/:id/:filename"

  # State Machine
  state_machine :state, :initial => :available do

    # Any user
    event :ask do
      transition :available => :waiting
    end

    # Device owner only
    event :assign do
      transition :waiting => :in_use
    end
    event :deny do
      transition :waiting => :available
    end
    event :receive do
      transition :in_use => :available
    end

    # Admin only
    event :make_unavailable do
      transition [:available, :in_use, :waiting] => :not_available
    end
    event :make_available do
      transition :not_available => [:available, :in_use, :waiting]
    end
  end


  # Methods
  
  def self.in_wait(requestor)
    self.where('id in (select book_id from requests where requestor = ? and  state = ?)', requestor , 'pending')
  end
  
  
  def self.search(query)
    q = "%#{query}%"
    self.where(["title LIKE ? OR author LIKE ? OR publication LIKE ? ", q, q, q])
  end

  def os_name
    "#{os} (#{os_version})"
  end

  def assign_to(user)
    
    self.possessor = user
    self.assign
  end

  def pending_request
    requests.pending.order("created_at desc").first
  end

  # Update the attributes, record and event with all the changes
  # List of changes is fetched from ActiveRecord::Dirty
  def update_attribs(params, comment)
    assign_attributes(params.except(*Book.protected_attributes))

    if owner_changed?
      BookMailer.ownership_email(owner_was, owner, self).deliver
    end

    # TODO: Put it elsewhere
    message = "Updated: <br />"
    message << changes.map do |k,v|
      "<b>#{k}</b>: '#{v[0]}' -> '#{v[1]}'"
    end.join("<br />")

    all_done = false

    ActiveRecord::Base.transaction do
      self.save!
      Event.record_event(self.id, message, comment)
      all_done = true
    end

    all_done
  end

  # List of all devices... but the ones owned by `current_user` should be 
  # displayed first... and therefore an Arel union is required for this!
  def self.list_for(u)
    d1, d2 = arel_table, arel_table

    # Owned by current_user
    d1 = d1.project('books.*').where(
      d1[:state].eq(:not_available).not
    ).where( d1[:owner].eq(u) )

    # Owned by others
    d2 = d2.project('books.*').where(
      d2[:state].eq(:not_available).not
    ).where( d2[:owner].eq(u).not )

    # TODO: refactor this!
    # Arel is not producing correct union syntax for UNION. It is surrounding
    # the whole SELECT by braces ( ).
    find_by_sql(d1.union(d2).to_sql.delete('()'))
  end

  def  get_issued_request
     self.requests.where(state: "issued").try(:first)
  end
end

app/models/book_type.rb
class BookType < ActiveRecord::Base
  attr_accessible :name

  validates :name, uniqueness: true, presence: true

  def self.get_book_type_id(book_type)
  	 BookType.find_by_name(book_type).try(:id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :login_required, :unless => [:format_json?, :format_xml?]
  before_filter :admin_required, only: [:new, :create, :edit, :update, :destroy, :unavailable]
  
  def format_json?
    request.format.json?
  end
  
  def format_xml?
    request.format.xml?
  end
  
  # GET /book_types.json
    def book_types    
    @book_types = BookType.all #list_for(current_user)
    respond_to do |format|
      format.json { render json: @book_types }
      format.xml { render xml: @book_types } 
    end
  end
  
  
  # GET /books
  def index    
    @books = Book.all #list_for(current_user)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books } 
      format.xml {
         username = params[:username]
         if username
           books = Book.where('id not in (select book_id from book_requests where username = ?)', username).reject { |book| book.possessor == username}
           render xml: books
          else
            render xml: @books 
         end  
         }
    end
  end

  # GET /admin/books/unavailable
  def unavailable
    @books = Book.unavailable

    respond_to do |format|
      format.html
      format.json { render json: @books }
      format.xml { render xml: @books }
    end
  end
  
  # GET /admin/books/waiting.xml
  def my_books_waiting
    username= params[:username]
    @books = Book.in_wait(username)
    respond_to do |format|
      format.xml { render xml: @books.empty? ? {}.to_xml(:root => 'books') : @books }
    end
  end
  
 
  # Exporting books list to a Excel file
  def export
    @books = Book.all
    respond_to do |format|
      format.xls do
        workbook = Spreadsheet::Workbook.new
        worksheet = workbook.create_worksheet(name: 'Books List')
        worksheet.row(0).concat [
          'Title',
          'author',
          'Publication',
          'Condition',
          'Review Link',
          'Type',          
          'Location',
          'State',
          'Possessor',
          'Property Of'
         # 'Owner'
        ] 
        @books.each_with_index { |device, i|
          worksheet.row(i+1).push(
            device.title,
            device.author,
            device.publication,
            device.condition,            
            device.link_for_review,
            device.book_type.try(:name),   
            device.location.location_name,        
            device.state,            
            device.possessor,
            device.property_of
           # device.owner
          )
        }

 
        header_format = Spreadsheet::Format.new(color: :green, weight: :bold)
        worksheet.row(0).default_format = header_format
        #output to blob object
        blob = StringIO.new('')
        workbook.write(blob)
        #respond with blob object as a file
        send_data(blob.string, :type => "application/ms-excel", :filename => "Books List.xls")
      end
    end
  end
  
  #Import Books Data from Excel
  def import
    if params[:book_import_file]
      imp_filename = params[:book_import_file].tempfile.path
      Spreadsheet.open(imp_filename) do |spreadsheet|
        ws = spreadsheet.worksheets.first

        # No worksheets
        if ws.nil?
          flash[:error] = 'No worksheets in the Excel sheet provided'
        else
          ws.each do |row|
            d = Book.new
            #break if row[0].nil?           
            d.title            = row[1]
            d.author           = row[2]
            d.publication      = row[3]
            d.condition        = row[4]
            d.link_for_review  = row[5] 
            d.book_type_id     = BookType.get_book_type_id(row[6])            
            d.location_id      = Location.find_by_location_name(row[7])
            d.possessor        = row[8]
            d.property_of      = row[9]
           # d.owner            = row[9]
           
            d.state            = :available
            d.save!

            Event.record_event(d.id, "Book has been imported")
          end
          flash[:notice] = 'Import successful, new records added to the database.'
        end
      end
    else
      flash[:error] = 'No file uploaded'
    end

    respond_to do |format|
      format.html { redirect_to books_path }
    end
  end

  # GET /books/search
  def search
    @books = Book.search(params[:q])
    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @books }
      format.xml {
        username = params[:username]
        book_type = params[:category]
        book_type_id = BookType.where("lower(name) like  ?", book_type.downcase).first if book_type
        if username
          if book_type_id
            books = Book.search(params[:q]).where(' (book_type_id = ?) and (id not in (select book_id from book_requests where username = ?))', book_type_id, username).reject { |book| book.possessor == username}
          else
            books = Book.search(params[:q]).where('id not in (select book_id from book_requests where username = ?)', username).reject { |book| book.possessor == username}
          end
          render xml: books.empty? ? {}.to_xml(:root => 'books') : books
        else
          render xml: @books.empty? ? {}.to_xml(:root => 'books') : @books
        end
      }
    end
  end

  # GET /books/1
  def show
    @book = Book.find(params[:id])
    @events = @book.events.limit(10)
    @comments = Review.find_all_by_book_id(params[:id])
    @comment = Review.new    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
      format.xml { render xml: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @book }
    end
  end

  # POST /books
  # POST /books.json
  def create
    params[:book].merge!({:created_by => current_user})
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        Event.record_event(@book.id, "book has been created")
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        flash.now[:error] = "Some errors prevented the book from saving"
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  def update
    @book = Book.find(params[:id])

    if params[:book][:book_possessor].present?
      params[:request] = {from_date: Date.today, to_date: (Date.today + 21.days)}
      make_request(params[:book][:book_possessor], false)
      @req.owner = current_user
      @req.approve            
    end
    params[:book].delete(:book_possessor)
    

    params[:book].merge!({:updated_by => current_user})
    respond_to do |format|
      if @book.update_attribs(params[:book], params[:comment])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render json: @book, status: :updated, location: @book }
      else
        flash.now[:error] = "Some errors prevented the data from updating"
        format.html { render action: "edit" }
      end
    end
  end

  def make_request(requestor, send_email)
    ActiveRecord::Base.transaction do
      @book.ask!
      @req = @book.requests.build(params[:request]) do |req|
        req.owner     = @book.owner
        req.requestor = requestor
        req.send_email = send_email
      end

      @req.save!
      @asked = true
    end
  end

  # PUT /books/:id/ask.js
  def ask
    @book = Book.find(params[:id])
    make_request(current_user, true)
    @books = Book.all
    respond_to do |format|
      if @asked
        flash.now[:notice] = 'Sent a request successfully.'
        format.html { redirect_to books_path }
        format.json { render json: @book, status: :requested, location: @book }
      else
        flash.now[:error] = 'Unable to add a request.'
        format.html { redirect_to books_path }
        format.json { render json: @book, status: :request_failed, location: @book }
      end
    end
  end
  
   # POST /books/:id/ask_book.xml
   # GET /books/:id/ask_book.xml
    
   def ask_book
    @book = Book.find(params[:id])
    user_name = params[:username]
    from_date = Time.now
    to_date = Time.now + 21.days
    params[:request] =  {:from_date=> from_date.strftime('%d-%m-%Y'), 
                         :to_date=> to_date.strftime('%d-%m-%Y')}
    
    make_request(user_name, true)
    respond_to do |format|
      if @asked
        format.xml  {render :xml => {:status => "success"}.to_xml(:root => 'ask-book')}
      else
        format.xml  {render :xml => {:status => "failed"}.to_xml(:root => 'ask-book')}
      end
    end
  end 
    
  

  def queue_request
    @book = Book.find(params[:id])
    username = current_user
    username = params[:username] unless username
    book_request = BookRequest.new(:book_id => @book.id, :username => username)
    @books = Book.all
    if book_request.save
      respond_to do |format|
        format.html {redirect_to books_path }
        format.xml  {render :xml => {:status => "success"}.to_xml(:root => 'queue-request')}
      end
    else
      respond_to do |format|
        format.html { redirect_to books_path }
        format.xml  {render :xml => {:status => "failed"}.to_xml(:root => 'queue-request')}
      end
    end  
  end 

  def dequeue_request
    @book = Book.find(params[:id])
    username = current_user
    username = params[:username] unless username
    book_request = BookRequest.where(:book_id => @book.id, :username => username).try(:first)

app/helpers/books_helper.rb
module BooksHelper
  def device_actions(device)
    case device.state.to_sym
    when :available
      if !Request.has_max_req_reached?(current_user)
        link_to 'Request', '#device-actions', class: 'btn btn-mini btn-primary request-device', id: "request-device-#{device.id}"

      end
    when :in_use
        if(BookRequest.requests_in_queue(device.id, current_user).present?)
            form_tag("/books/#{device.id}/dequeue_request", :method => "put") do 
              submit_tag 'De Queue',  class: 'btn btn-mini btn-primary request-device-dequeue'    
            end             
        elsif(BookRequest.find_all_by_username(current_user).size < 2)       
          form_tag("/books/#{device.id}/queue_request", :method => "put") do 
            submit_tag '+Queue',  class: 'btn btn-mini btn-primary request-device-queue'    
        end unless (current_user == device.possessor)
        end
       
    when :waiting
      link_to(
        'Waiting', '#device-actions',
        :class => 'btn btn-mini waiting-device disabled', :id => "waiting-device-#{device.id}",
        'rel' => 'popover', 'data-content' => "This device has already been requested by `#{device.requests.pending.first.try(:requestor)}`",
        'data-original-title' => 'Waiting Approval'
      )
    when :not_available
      if is_admin?
        link_to 'Edit', edit_book_path(device)
      end
    end
  end
end

app/views/books/_form.html.haml
= labeled_form_for @book, html: {id: 'device-form', class: 'form-horizontal new_book', multipart: true} do |f|
  .hide
    = hidden_field_tag :comment
  .row-fluid
    .span6
      = f.select     :book_type_id, BookType.all.map {|dt| [dt.name, dt.id]}
      = f.text_field :title,        title: t('device.form.title'), label: 'Title'
      = f.text_field :author,        title: t('device.form.author'), label: 'Author'
      = f.text_field :publication,           title: t('device.form.publication'),          label: 'Publication'
   
      -if !f.object.id.blank? and @book.available? and is_admin?    
        =f.text_field :book_possessor, label: 'Possessor',  placeholder: 'LDAP Username', class: 'typeahead', autocomplete: 'off' 
      = f.text_field :condition,  title: t('device.form.condition')
      = f.text_field :isbn,  title: t('device.form.isbn'), label: 'ISBN'
   
      /= f.text_field :owner,        class: 'typeahead', placeholder: 'Start typing in the user name',  autocomplete: 'off', label: 'Admin'
      = f.text_field :property_of,  title: t('device.form.property_of'), label: 'Contributed By'
      = f.text_field :link_for_review,   title: t('device.form.review_link'),  label: 'Review Link'
      = f.select  :location_id,  Location.all.collect {|p| [ p.location_name, p.id ] }
    
    .span6.imageposition        
      .img-placeholder.small
        -if f.object.image_link.blank?      
          = image_tag  "/assets/book.jpg", id: 'book_image'
        -else
          = image_tag  @book.image_link, id: 'book_image'
    %br
    .span6.imagelink        
      = f.text_field :image_link,  title: t('device.form.imagelink'),  label: 'Image Link'
    

    / .span6
    /   = f.file_field :book_photo
      
    /   = f.text_field :phone_num,        title: t('device.form.phone_num'),       label: 'Phone Number'
      
  / Accessories
  / %h3= accessories_heading(@device)
  / = f.fields_for :accessories do |accessories_fields|
  /   = render 'accessories/form', :f => accessories_fields

  / = render 'accessories/form_template'

  / .well#add-accessory-container.center
  /   %a.btn.btn-primary#add-accessory
  /     %i.icon-plus.icon-white
  /     Add Accessory

  .actions
    = f.submit :class => "btn btn-primary btn-large", :id => @book.new_record? ? 'create-device' : 'update-device'

app/views/books/_list.html.haml
%table#device-list.table.table-striped.table-bordered
  %thead
    %tr
      %th Title
      %th Author
      %th Publication
      %th Review Link 
      %th Category
      /%th Admin
      %th Location
      %th Reviews
      %th Condition
      %th Availability
      %th 
      %th Due&nbsp;Date
  %tbody
    - @books.each do |book|
      %tr.clickable{'data-url' => book_path(book)}
        %td.wrapper= "#{book.title}"
        %td.wrapper= book.author
        %td.wrapper= "#{book.publication}"
        %td.wrapper 
          = link_to book.link_for_review, book.link_for_review
        %td.wrapper= book.try(:book_type).try(:name)
        /%td.wrapper= book.owner
        %td.wrapper= book.location.location_name
        %td.wrapper
          = link_to  "Reviews", "#{book_path(book)}#reviews"
        %td.wrapper=book.condition
        %td.wrapper
          = state_label(book)
        %td.wrapper.device-actions{id: "device-actions-#{book.id}"}= device_actions(book)
        %td.wrapper= end_label(book)

  %tfoot
    %tr
      %td
        %input.search_init{:name => "search_make", :type => "text", :value => "Search Title"}/
      %td
        %input.search_init{:name => "search_label", :type => "text", :value => "Search Author"}/
      %td
        %input.search_init{:name => "search_os", :type => "text", :value => "Search Application"}/
      %td
        %input.search_init{:name => "search_serial", :type => "text", :value => "Search Review Link"}/
      %td
        %input.search_init{:name => "search_project", :type => "text", :value => "Search Category"}/
      %td
        %input.search_init{:name => "search_location", :type => "text", :value => "Search Location"}/
      %td
      %td
      %td
      %td
      %td
      
%br
#device-actions.modal.fade

= render 'books/request_form_template'

app/views/books/_request_form_template.html.haml
%script#device-actions-template{type: 'text/x-jquery-tmpl'}
  .modal-header
    %h3
      Request for the book
      %button.close{"data-dismiss" => "modal", :type => "button"}
        %i.icon-remove
  .modal-body

    %form.form.form-inline.request_device{"accept-charset" => "UTF-8", :action => "/books/${deviceId}/ask", :method => "post", :id => "request_device_${deviceId}"}
      %div{:style => "margin:0;padding:0;display:inline"}
        %input{:name => "utf8", :type => "hidden", :value => "✓"}/
        %input{:name => "_method", :type => "hidden", :value => "put"}/
        %input{:name => "authenticity_token", :type => "hidden", :value => form_authenticity_token}/

      .instructions
        By requesting this book, an email is sent out to the owner of the book,
        who will in turn approve your request. By default it is a period of 21 days.

      = fields_for :request do |r|
        #startdate.datepicker.input-append.date{"data-date" => format_date(Date.today), "data-date-format" => "dd-mm-yyyy"}
          = r.label :from_date
          = r.text_field :from_date, value: format_date(Date.today), class: 'span2', readonly: true
          /%span.add-on
          / %i.icon-th
        #enddate.datepicker.input-append.date{"data-date" => '', "data-date-format" => "dd-mm-yyyy"}
          = r.label :to_date
          = r.text_field :to_date, value: format_date(Date.today + 21.days), class: 'span2', :readonly => true
          /%span.add-on
          /  %i.icon-th

      %p.centered-info
        %input.request-button.btn.btn-primary{:type => :submit, :value => 'Request'}
        .progress.progress-striped.active.hide
          .bar{style: 'width: 100%'}
  .modal-footer
    .action-buttons
      %a.btn{"data-dismiss" => "modal"} Close

app/views/books/ask.js.haml
:plain
  $('.progress').hide()
  $('.request-button').replaceWith("#{escape_javascript(render 'shared/flashes')}")
  $('#device-actions-#{@book.id}').html("#{escape_javascript(device_actions(@book))}")
  $('#device-list').replaceWith("#{escape_javascript(render 'books/list')}")
  $('#waiting-device-#{@book.id}').popover()

app/views/books/edit.html.haml
.pager
  %li.previous
    = link_to '<< Books List', books_path

.well
  %legend.row-fluid
    .pull-left
      %h2
        Editing
        = device_name(@book)
    .pull-right
      = state_label(@book)
      - if @book.not_available?
        = link_to 'Make Available', make_available_book_path(@book), method: :put, class: 'btn btn-primary', data: {confirm: 'Are you sure you want to make this book available?'}
      - else
        = link_to 'Make Unavailable', make_unavailable_book_path(@book), method: :put, class: 'btn btn-warning', data: {confirm: 'Are you sure you want to make this book unavailable?'}

  .row-fluid
    = render 'form'

#update-device-modal.modal.fade
  .modal-header
    %h3
      Reason for updation
      %button.close{"data-dismiss" => "modal", :type => "button"}
        %i.icon-remove
  .modal-body
    .instructions
      You can add some comments here:
    %form.form
      %textarea{name: :comment}
      %p.centered-info
        %input.btn.btn-primary{:type => :submit, :value => 'Update'}
  .modal-footer
    .action-buttons
      %a.btn{"data-dismiss" => "modal"} Close

app/views/books/index.html.haml
.row-fluid
  .pull-left
    %h2 Listing Books
  .pull-right
    - if is_admin?
      %a.btn.btn-primary{href: new_book_path}
        %i.icon-plus.icon-white
        Add Book
  - if is_admin?
    .pull-right.export-to-excel
      = link_to 'Export To Excel', export_books_path(:format => :xls), class: 'btn'


%legend

- if @books.empty?
  .no_device
    There are no books in the database at the moment. 
    -if is_admin?
      Go to 
      = link_to 'create page', new_book_path
      to add a book.
- else
  = render 'books/list'

- if is_admin?
  .row-fluid
    .span6
      = form_tag import_books_path, :class => "well form form-vertical", :multipart => true do
        %h3 Import an Excel
        = file_field_tag :book_import_file
        %br/
        = submit_tag 'Import', class: 'btn btn-primary'

app/views/books/new.html.haml
.well
  %legend.row-fluid
    .pull-left
      %h2 New book

  .row-fluid
    = render 'form'

app/views/books/search.html.haml
%h2 Search Results
%legend
- if @books.empty?
  .no_device
    There are no books matching your search criteria in the database at the moment.
- else
  = render 'books/list'
%br/
= link_to 'All Books', books_path, class: 'btn'

app/views/books/show.html.haml
.pager
  %li.previous
    = link_to '<< Books List', books_path

  .pull-right
    - if is_admin?
      %a.btn.btn-primary{href: new_book_path}
        %i.icon-plus.icon-white
        Add Book
.well
  %legend.row-fluid
    .pull-left
      %h2= @book.title
    .pull-right
      = state_label(@book)
      - if is_admin?
        = link_to 'Edit', edit_book_path(@book), class: 'btn btn-medium'
  .row-fluid
    .span4
      .field     
        %b Author:
        = "#{@book.author}"
      .field
        %b Publication:
        = "#{@book.publication}"
      .field
        %b Category:
        = "#{@book.book_type.name}"
      .field
        %b State:
        = "#{@book.state}"
      .field
        %b ISBN:
        = "#{@book.isbn}"
      .field
        %b Possessor:
        - if @book.available?
          %span.label.label-info None
        - else
          = "#{@book.possessor}"
          - if @book.in_use? and (is_admin? or is_owner?(@book))
            = link_to 'Receive', receive_book_path(@book), method: :put, class: 'btn btn-primary btn-mini'
      .field
        %b Created On:
        = "#{@book.created_at.strftime('%d-%m-%y')}"
      .field
        %b Created By:
        = "#{@book.created_by}"
    .span4    
      .field
        %b Condition:
        = @book.condition
      .field
        %b Review Link:
        = link_to "#{@book.link_for_review}", "#{@book.link_for_review}"
      .field
        %b Location:
        = "#{@book.location.location_name}"
      .field
        %b Contributed By:
        = "#{@book.property_of}"
      .field
        %b Book Id:
        = "#{@book.id}"
      .field
        %b Updated On:
        = "#{@book.updated_at.strftime('%d-%m-%y')}"
      .field
        %b Updated By:
        = !@book.updated_by.blank? ? "#{@book.updated_by}" : "#{@book.created_by}"
    .span4
      .img-placeholder.small
        -if @book.image_link.blank?
          = image_tag "/assets/book.jpg"
        -else
          = image_tag @book.image_link


#reviews.well
  = render 'reviews/list'
#reviews_form.well
  = render 'reviews/form'


.well
  %h3 History
  - if @events.empty?
    No events associated for this book so far!
  - else
    = render 'events/list', events: @events
    = link_to 'See all events', book_events_path(@book)

app/views/books/unavailable.html.haml
.row-fluid
  .pull-left
    %h2 Unavailable Books

%legend

- if @books.empty?
  .no_device
    There are no unavailable books in the database at the moment. All good!
- else
  = render 'books/list'