config/routes.rb
DeviceInventory::Application.routes.draw do

  get '/signin' => 'sessions#new'
  delete'/signout' => 'sessions#destroy'

  resources :books do
    collection do
      get :search
      get :export
      get :unavailable
      post :import
      get :my_books_current
      get :my_books_history
      get :my_books_waiting
    end

    member do
      put :ask
      put :receive
      put :make_unavailable
      put :make_available
      put :queue_request
      put :dequeue_request
      put  :ask_book
      post :ask_book
      get  :ask_book
      post :queue_request
      get  :queue_request
      post :dequeue_request
      get  :dequeue_request
      
    end

    resources :accessories
    resources :reviews
    resources :events, only: [:index]
  end

  resources :users do
    collection do
      get :search
    end
  end

  resources :requests, only: [:index] do
    member do
      put :approve
      put :reject
    end
  end

  resources :sessions

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :book_types
    resources :administrators do
      collection do
        get :search
      end
    end
  end
  
  match 'book_types' => 'books#book_types'
  match 'authentication' => 'sessions#authenticate'

  root :to => 'books#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BookInventory
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} Book Inventory
          .btn-group.pull-right
            %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.icon-user
              = user_signed_in? ? current_user : 'Guest'
              %span.caret
            %ul.dropdown-menu
              - if user_signed_in?
                %li= link_to("Sign Out", signout_path, :method => :delete)
              - else
                %li= link_to 'Sign In', signin_path
          .nav-collapse
            %ul.nav.pull-left
              %li= link_to 'Home', root_path
              - if user_signed_in?
                - if is_admin?
                  %li= link_to "Dashboard", admin_dashboard_path
                  %li
                    %a{href: requests_path}
                      Requests
                      %span.badge.badge-important= Request.pending_count(current_user)
                / %li
                /   %a{href: REPORT_GENERATOR_URL, target: '_blank'}
                /     Reports
            %ul.nav.pull-right
              %li
                %form.navbar-form.pull-right{action: search_books_path}
                  %input.span3{type: :text, name: 'q', placeholder: 'Search Books'}
          / /.nav-collapse
    .container
      .hero-unit
        = render 'shared/flashes'
        = yield
      %hr/
      %footer
        %p &copy; Copyright.Imaginea.2012.
    / /.container